propiedad:
  ejemplo: Hola Docker


spring:
  datasource:
    url: jdbc:mysql://192.168.54.192:3306/clientes
    username: clientes
    password: 'secreto'

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/