propiedad:
  ejemplo: Hola Default

server:
  port: 8081

spring:
  flyway:
    locations: classpath:/db/migration,classpath:/db/testdata

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true