propiedad:
  ejemplo: Hola Default

server:
  port: 8082

spring:
  flyway:
    locations: classpath:/db/migration,classpath:/db/testdata
  # Configuracion Requerida como Resource Server
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      # deals with single and multi-valued JWT claims
      accept-single-value-as-array: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${openid.jwt.issuerUri}
          jwk-set-uri: ${openid.jwt.issuerUri}/protocol/openid-connect/certs

# Habilitar todos los endpoints de Spring Boot Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by_default: true
    health:
      show-details: always
      circuitbreakers.enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true


# Configuracion de Circuit Breaker
resilience4j.circuitbreaker:
  circuitBreakerAspectOrder: 2
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 10
      waitDurationInOpenState: 50s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
  instances:
    clientes:
      baseConfig: default
      failureRateThreshold: 20

# Configuracion de Retry
resilience4j.retry:
  retryAspectOrder: 3
  instances:
    clientes:
      maxAttempts: 3
      waitDuration: 1s

## Configuracion de Bulkhead
#resilience4j.bulkhead:
#  instances:
#    clientes:
#      maxWaitDuration: 10ms
#      maxConcurrentCalls: 10